---
version: '3.4'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "finance"]
      interval: 5s
      retries: 5
    env_file:
      - local.env

  bank-api:
    image: bank-api:0.1.0
    container_name: bank_api
    ports:
      - "8080:8080"
    env_file:
      - local.env

  scylla-node1:
    container_name: scylla-node1
    image: scylladb/scylla:5.1.0
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
      - "./scylla/mutant-data.txt:/mutant-data.txt"

  scylla-node2:
      container_name: scylla-node2
      image: scylladb/scylla:5.1.0
      restart: always
      command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
      volumes:
        - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
        - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"

  scylla-node3:
      container_name: scylla-node3
      image: scylladb/scylla:5.1.0
      restart: always
      command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
      volumes:
        - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
        - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

volumes:
  minio_data:
  scylla_data:
  scylla_manager_db_data:
