name: Dev - Copy DAGs to GCS

on:
  pull_request:
  workflow_dispatch:
#
permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  format:
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v2
      - name: format check
        run: sbt scalafmtCheck

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
            java-version: '11'
            distribution: 'temurin'
            cache: 'sbt'
      - name: Run tests
        run: sbt coverage test
      - name: Coverage Report
        run: sbt coverageReport
      - name: mv report
        run: mv ./target/scala-3.3.1/scoverage-report/scoverage.xml .
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: scoverage.xml


