name: Dev - Copy DAGs to GCS

on:
  pull_request:
  workflow_dispatch:
#
permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: format check
        run: sbt scalafmtCheck

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
            java-version: '11'
            distribution: 'temurin'
            cache: 'sbt'
      - name: Run tests
        run: sbt coverage test
      - name: Coverage Report
        run: sbt coverageReport
      - name: Code Coverage Summary Report
        uses: insightsengineering/coverage-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: "./target/scala-3.3.1/coverage-report/cobertura.xml"
          threshold: 75
          fail: true
          diff: true
          diff-branch: main
          diff-storage: _xml_coverage_reports
          coverage-summary-title: "Code Coverage Summary"


