name: Dev - Copy DAGs to GCS

on:
  pull_request:
  workflow_dispatch:
#
permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: format check
        run: sbt scalafmtCheck

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
            java-version: '11'
            distribution: 'temurin'
            cache: 'sbt'
      - name: Run tests
        run: sbt coverage test
      - name: Coverage Report
        run: sbt coverageReport

  build_artifact:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Create Docker Image
        run: sbt docker:publishLocal


